version: '3.5'
services:
  database:
    build: 
      context: './'
      dockerfile: './.docker/Dockerfile'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistramit
      MYSQL_USER: sistramit
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      [db-volume:/var/lib/mysql]  
volumes:
  db-volume: